### ISSUE TITLE
为何要自己写bio.c？

### ISSUE THREAD

**Issue by helloray** [geminiwen/libuv-mbedtls#1]
mbedtls已经提供了mbedtls_net_send/mbedtls_net_recv, 使用前自己创建socket并设置成非阻塞即可，    然后调用mbedtls_ssl_set_bio( &tls, &sockfd, mbedtls_net_send, mbedtls_net_recv, NULL );
自己提供bio.c的目的是为何，不大明白

**Comment by geminiwen** [comment]
因为不想把 socket 的 IO 操作从 libuv 里面暴露出去。。
